project_id = "vmijvdxllubdudppeemr"

[functions.manage-products]
verify_jwt = false

[functions.bulk-upsert-products]
verify_jwt = false

[functions.trigger-snapshot-new]
verify_jwt = false

[functions.sync-from-remote]
verify_jwt = false

[functions.remote-probe]
verify_jwt = false

[functions.apply-web-skus-sync]
verify_jwt = false

[functions.get-users-with-roles]
verify_jwt = false

[functions.match-candidates]
verify_jwt = false

[functions.choose-candidate]
verify_jwt = false