project_id = "vmijvdxllubdudppeemr"

[functions.sync-from-remote-multi]
verify_jwt = false

[functions.bulk-upsert-products]
verify_jwt = false

[functions.export-products]
verify_jwt = false

[functions.remote-tip-produs]
verify_jwt = false

[functions.sync-tip-produs]
verify_jwt = false

[functions.get-users-with-roles]
verify_jwt = false

[functions.sync-processed-from-remote]
verify_jwt = false

[functions.align-resource-ids]
verify_jwt = false

[functions.sync-local-to-remote]
verify_jwt = false

[functions.sync-resource-to-remote]
verify_jwt = false

[functions.sync-product-to-remote]
verify_jwt = false

[functions.processing-queue]
verify_jwt = false

[functions.trigger-snapshot]
verify_jwt = false

[functions.trigger-snapshot-new]
verify_jwt = false

[functions.remote-resources]
verify_jwt = false
