-- First, we need to drop the existing primary key and create a new one on erp_product_code
-- Also change article_id to be identity without autoincrement

-- Drop existing primary key
ALTER TABLE public.products DROP CONSTRAINT IF EXISTS products_pkey;

-- Make erp_product_code NOT NULL and set as primary key
ALTER TABLE public.products ALTER COLUMN erp_product_code SET NOT NULL;
ALTER TABLE public.products ADD PRIMARY KEY (erp_product_code);

-- Drop article_id column and recreate as identity without autoincrement
ALTER TABLE public.products DROP COLUMN article_id;
ALTER TABLE public.products ADD COLUMN article_id INTEGER GENERATED BY DEFAULT AS IDENTITY;

-- Add index on article_id for better query performance
CREATE INDEX idx_products_article_id ON public.products(article_id);