-- Update products table schema to match specification

-- Add missing tosync column
ALTER TABLE products 
ADD COLUMN IF NOT EXISTS tosync numeric DEFAULT '0'::numeric;

-- Handle primary key constraints
DO $$ 
BEGIN
  -- Check if primary key exists on articol_id
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint 
    WHERE conname = 'products_pkey' 
    AND conrelid = 'products'::regclass
  ) THEN
    -- No primary key exists, add it
    ALTER TABLE products ADD CONSTRAINT products_pkey PRIMARY KEY (articol_id);
  ELSIF NOT EXISTS (
    SELECT 1 FROM pg_constraint 
    WHERE conname = 'products_pkey' 
    AND conrelid = 'products'::regclass
    AND conkey = ARRAY[(SELECT attnum FROM pg_attribute WHERE attrelid = 'products'::regclass AND attname = 'articol_id')]
  ) THEN
    -- Primary key exists but not on articol_id, need to recreate
    ALTER TABLE products DROP CONSTRAINT products_pkey;
    ALTER TABLE products ADD CONSTRAINT products_pkey PRIMARY KEY (articol_id);
  END IF;
END $$;

-- Add unique constraint on articol_id if not exists
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint 
    WHERE conname = 'products_articol_id_key' 
    AND conrelid = 'products'::regclass
  ) THEN
    ALTER TABLE products ADD CONSTRAINT products_articol_id_key UNIQUE (articol_id);
  END IF;
END $$;

-- Ensure unique constraint on erp_product_code
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint 
    WHERE conname = 'products_erp_product_code_key' 
    AND conrelid = 'products'::regclass
  ) THEN
    ALTER TABLE products ADD CONSTRAINT products_erp_product_code_key UNIQUE (erp_product_code);
  END IF;
END $$;

-- Convert articol_id to identity column if not already
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_attribute 
    WHERE attrelid = 'products'::regclass 
    AND attname = 'articol_id' 
    AND attidentity != ''
  ) THEN
    ALTER TABLE products ALTER COLUMN articol_id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;